FROM golang:1.24.1 AS builder

WORKDIR /src/server

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /src/server/server .
COPY --from=builder /src/server/data ./data

ENTRYPOINT ["./server"]