services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: src/server/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TICK_MS: ${TICK_MS}
    ports:
      - "8080:8080"

  client:
    build:
      context: src/client/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      API_URL:  ${API_URL}
    ports:
      - "23234:23234"

  migrate:
    image: golang:1.24.1
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./src/server/sql/schema:/migrations
    entrypoint:
      [
        "/bin/sh",
        "-c",
        'go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir /migrations postgres "postgres://$DB_USER:$DB_PASSWORD@db:$DB_PORT/$DB_NAME?sslmode=disable" up',
      ]

volumes:
  postgres_data:
