// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: actions.sql

package database

import (
	"context"
)

const getActionByID = `-- name: GetActionByID :one
SELECT id, name, created_at, updated_at FROM actions
WHERE id = $1
`

func (q *Queries) GetActionByID(ctx context.Context, id int32) (Action, error) {
	row := q.db.QueryRowContext(ctx, getActionByID, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllActions = `-- name: GetAllActions :many
SELECT id, name FROM actions
`

type GetAllActionsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAllActions(ctx context.Context) ([]GetAllActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActionsRow
	for rows.Next() {
		var i GetAllActionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
