// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: inventories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories(id, user_id, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	NOW(),
	NOW()
)
RETURNING id, user_id, position_x, position_y, created_at, updated_at
`

func (q *Queries) CreateInventory(ctx context.Context, userID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, userID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT id, user_id, position_x, position_y, created_at, updated_at from inventories
WHERE id = $1
`

func (q *Queries) GetInventory(ctx context.Context, id pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
