// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getItemByResourceId = `-- name: GetItemByResourceId :one
SELECT id, name, created_at, updated_at FROM items
WHERE id = (SELECT item_id FROM resources WHERE resources.id = $1)
`

func (q *Queries) GetItemByResourceId(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByResourceId, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
