// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Action struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Character struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	PositionX    int32
	PositionY    int32
	ActionID     int32
	ActionTarget uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Grid struct {
	PositionX int32
	PositionY int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Inventory struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	PositionX int32
	PositionY int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Item struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Resource struct {
	ID             uuid.UUID
	ResourceNodeID uuid.UUID
	ItemID         uuid.UUID
	DropChance     string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ResourceNode struct {
	ID        uuid.UUID
	Name      sql.NullString
	PositionX int32
	PositionY int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
