// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Character struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	PositionX    int32
	PositionY    int32
	ActionID     int32
	ActionTarget pgtype.UUID
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Grid struct {
	PositionX int32
	PositionY int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Inventory struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PositionX int32
	PositionY int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Item struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type RefreshToken struct {
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type Resource struct {
	ID             pgtype.UUID
	ResourceNodeID pgtype.UUID
	ItemID         pgtype.UUID
	DropChance     int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ResourceNode struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	PositionX int32
	PositionY int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
