// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: actions.sql

package database

import (
	"context"
)

const createAction = `-- name: CreateAction :exec
INSERT INTO actions (name) VALUES ($1)
`

func (q *Queries) CreateAction(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createAction, name)
	return err
}

const getActionById = `-- name: GetActionById :one
SELECT id, name, required_tool_type_id FROM actions
WHERE id = $1
`

func (q *Queries) GetActionById(ctx context.Context, id int32) (Action, error) {
	row := q.db.QueryRow(ctx, getActionById, id)
	var i Action
	err := row.Scan(&i.ID, &i.Name, &i.RequiredToolTypeID)
	return i, err
}

const getActionByName = `-- name: GetActionByName :one
SELECT id, name, required_tool_type_id FROM actions
WHERE name = $1
`

func (q *Queries) GetActionByName(ctx context.Context, name string) (Action, error) {
	row := q.db.QueryRow(ctx, getActionByName, name)
	var i Action
	err := row.Scan(&i.ID, &i.Name, &i.RequiredToolTypeID)
	return i, err
}

const getAllActions = `-- name: GetAllActions :many
SELECT id, name FROM actions
`

type GetAllActionsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAllActions(ctx context.Context) ([]GetAllActionsRow, error) {
	rows, err := q.db.Query(ctx, getAllActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActionsRow
	for rows.Next() {
		var i GetAllActionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
