// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: grid.sql

package database

import (
	"context"
)

const getGrid = `-- name: GetGrid :many
SELECT position_x, position_y FROM grid
`

func (q *Queries) GetGrid(ctx context.Context) ([]Grid, error) {
	rows, err := q.db.Query(ctx, getGrid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grid
	for rows.Next() {
		var i Grid
		if err := rows.Scan(&i.PositionX, &i.PositionY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
