// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: grid.sql

package database

import (
	"context"
)

const createGridItem = `-- name: CreateGridItem :exec
INSERT INTO grid (position_x, position_y) VALUES ($1, $2)
`

type CreateGridItemParams struct {
	PositionX int32
	PositionY int32
}

func (q *Queries) CreateGridItem(ctx context.Context, arg CreateGridItemParams) error {
	_, err := q.db.Exec(ctx, createGridItem, arg.PositionX, arg.PositionY)
	return err
}

const getGrid = `-- name: GetGrid :many
SELECT position_x, position_y FROM grid
`

func (q *Queries) GetGrid(ctx context.Context) ([]Grid, error) {
	rows, err := q.db.Query(ctx, getGrid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grid
	for rows.Next() {
		var i Grid
		if err := rows.Scan(&i.PositionX, &i.PositionY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
