// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: items.sql

package database

import (
	"context"
)

const getItemById = `-- name: GetItemById :one
SELECT id, name, created_at, updated_at FROM items
WHERE id = $1
`

func (q *Queries) GetItemById(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRow(ctx, getItemById, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByResourceId = `-- name: GetItemByResourceId :one
SELECT id, name, created_at, updated_at FROM items
WHERE id = (SELECT item_id FROM resources WHERE resources.id = $1)
`

func (q *Queries) GetItemByResourceId(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByResourceId, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
