// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	ID                 int32
	Name               string
	RequiredToolTypeID pgtype.Int4
}

type Character struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Name                 string
	PositionX            int32
	PositionY            int32
	ActionID             int32
	ActionTarget         pgtype.Int4
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	ActionAmountLimit    pgtype.Int4
	ActionAmountProgress pgtype.Int4
}

type Grid struct {
	PositionX int32
	PositionY int32
}

type Inventory struct {
	ID          pgtype.UUID
	CharacterID pgtype.UUID
	PositionX   int32
	PositionY   int32
	Weight      int32
	Capacity    int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type InventoryItem struct {
	ID          pgtype.UUID
	ItemID      int32
	InventoryID pgtype.UUID
	Quantity    int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Item struct {
	ID         int32
	Name       string
	Weight     int32
	ToolTypeID pgtype.Int4
}

type RefreshToken struct {
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
}

type Resource struct {
	ID             int32
	ResourceNodeID int32
	ItemID         int32
	DropChance     int32
}

type ResourceNode struct {
	ID          int32
	Name        string
	ActionID    int32
	Tier        int32
	MinToolTier int32
}

type ResourceNodeSpawn struct {
	ID        int32
	NodeID    int32
	PositionX int32
	PositionY int32
}

type ToolType struct {
	ID   int32
	Name string
	Tier int32
}

type User struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Surname        pgtype.Text
}

type Version struct {
	ID        int32
	Value     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
