// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getResourcesByNodeId = `-- name: GetResourcesByNodeId :many
SELECT id, resource_node_id, item_id, drop_chance, created_at, updated_at FROM resources
WHERE resource_node_id = $1
`

func (q *Queries) GetResourcesByNodeId(ctx context.Context, resourceNodeID pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, getResourcesByNodeId, resourceNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ResourceNodeID,
			&i.ItemID,
			&i.DropChance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
