// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resourceNodes.sql

package database

import (
	"context"
)

const getResourceNodeById = `-- name: GetResourceNodeById :one
SELECT id, name, action_id, tier FROM resource_nodes WHERE id = $1
`

func (q *Queries) GetResourceNodeById(ctx context.Context, id int32) (ResourceNode, error) {
	row := q.db.QueryRow(ctx, getResourceNodeById, id)
	var i ResourceNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ActionID,
		&i.Tier,
	)
	return i, err
}
