// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_at, updated_at, email, hashed_password, surname)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2,
	$3
)
RETURNING id, email, hashed_password, created_at, updated_at, surname
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
	Surname        pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.HashedPassword, arg.Surname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surname,
	)
	return i, err
}

const getSurnameById = `-- name: GetSurnameById :one
SELECT surname FROM users
WHERE id = $1
`

func (q *Queries) GetSurnameById(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSurnameById, id)
	var surname pgtype.Text
	err := row.Scan(&surname)
	return surname, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, hashed_password, created_at, updated_at, surname from users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surname,
	)
	return i, err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetUsers)
	return err
}

const updateUserById = `-- name: UpdateUserById :one
UPDATE users
SET email = $2, 
	hashed_password = $3,
	updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, created_at, updated_at, surname
`

type UpdateUserByIdParams struct {
	ID             pgtype.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserById, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Surname,
	)
	return i, err
}
