// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: version.sql

package database

import (
	"context"
)

const createVersion = `-- name: CreateVersion :exec
INSERT INTO version (value, created_at, updated_at) VALUES ($1, NOW(), NOW())
`

func (q *Queries) CreateVersion(ctx context.Context, value string) error {
	_, err := q.db.Exec(ctx, createVersion, value)
	return err
}

const getVersion = `-- name: GetVersion :one
SELECT id, value, created_at, updated_at FROM version WHERE id = 1
`

func (q *Queries) GetVersion(ctx context.Context) (Version, error) {
	row := q.db.QueryRow(ctx, getVersion)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVersion = `-- name: UpdateVersion :exec
UPDATE version SET value = $1 WHERE id = 1
`

func (q *Queries) UpdateVersion(ctx context.Context, value string) error {
	_, err := q.db.Exec(ctx, updateVersion, value)
	return err
}
